### ISSUE TITLE
ClayIcon elementClasses

### ISSUE THREAD

**Issue by carloslancha** [metal/metal-clay-components#113]
We need to add elementClasses param to ClayIcon

**Comment by matuzalemsteles** [comment]
Hey @carloslancha,  Do you have a specific case for adding `elementClasses`?

**Comment by carloslancha** [comment]
We will need it in order to use the component in portal @matuzalemsteles

**Comment by jbalsas** [comment]
Hey @carloslancha, could you please document here:
- What's the current usage in JSP: `<aui:icon ...  />`
- What's the currently generated markup for that: `<span>...</span>`
- What's the currently generated markup of the component here

I think that would help document the usecases and needs for the components :)

**Comment by carloslancha** [comment]
@jbalsas I was preparing a Google Doc with the analysis of each taglib but maybe we can add an issue for each one and track it here?

**Comment by jbalsas** [comment]
Let's create an Electric site!! 🎉

**Comment by matuzalemsteles** [comment]
@jbalsas Looks good!

@carloslancha Patrick has updated the use of `icon-monospaced`, will have to wrap it inside a `span` and add `icon-monospaced`, we have to update` clay-icon`.

**Comment by carloslancha** [comment]
@jbalsas sure!

@matuzalemsteles do we have an issue, a ticket or something for that? ClayIcon is used by a lot of components and maybe this change is not trivial at all...

**Comment by matuzalemsteles** [comment]
@carloslancha the change has already been pushed into the portal. @pat270 can tell us something else about this.

**Comment by carloslancha** [comment]
@pat270 @matuzalemsteles Looking at the clay's Changelog I found that icon-monospaced has been removed so... What should be the final markup?

**Comment by matuzalemsteles** [comment]
Hey @carloslancha,

When `monospaced` is true, the `icon-monospace` class must wrap the `icon` in a `span`. example:
```html
<span class="icon-monospaced">
    <svg...</svg>
</span>
```

**Comment by carloslancha** [comment]
About icon-monospaced stuff is already clear an solved in https://github.com/metal/metal-clay-components/issues/122

Electric site for migration guides, notes and problems has been created and will be available soon.

So... let's add elementClasses param to ClayIcon :P
