### ISSUE TITLE
ClayAlert icons

### ISSUE THREAD

**Issue by atjuan** [metal/metal-clay-components#120]
Success and warning icons are not correct. See mockup for reference.

**Comment by matuzalemsteles** [comment]
Thanks @juanantonLR!

Hey @carloslancha, we can remove the responsibility of passing the icon via `soy` in `ClayAlert` and passing the icons by css. Just like Patrick did in `ClayModal` #119. What do you think?

@pat270 you can do it ?

**Comment by pat270** [comment]
@juanantonLR the icons for success and warning don't exist in Clay, we need to add the svg's. Not related to this but we are also missing caret-right and caret-left

**Comment by carloslancha** [comment]
Just to leave it write here we're not going to pass the icons by css so we continue passing them  via soy.

Task in JIRA: https://issues.liferay.com/browse/LEXI-203

**Comment by matuzalemsteles** [comment]
This was fixed at #134.
