### ISSUE TITLE
Organization of the packages

### ISSUE THREAD

**Issue by matuzalemsteles** [metal/metal-clay-components#121]
Hey guys,

We can improve the organization of packages in `packages`, we have some packages like` generator-clay` and `browserslist-config-clay-components` that are somewhat inconsistent with the` clay-`tag.

I think of the following structure.
```
.
+-- packages
|   +-- clay/
|   +-- utility or utils/
```
```
.
+-- packages/
+-- utility/
```

What do you think about this ?

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, does lerna even work that way? I was under the impression that all packages should live as first-level-folders inside the `packages/` folder.

Even if lerna could work in this other way, I haven't seen any big lerna project organizing packages in this way (see [jest](https://github.com/facebook/jest/tree/master/packages) for example), nor I think it brings a lot of benefits to the table.

**Comment by matuzalemsteles** [comment]
Hey @jbalsas, Yes, we can work with Lerna, I believe that the benefit would be to centralize only clay components in one place as that quantity starts to grow, and utilitarian packages in others. Maybe more like a form of organization.

**Comment by jbalsas** [comment]
I’d rather extract the tools to external repos 😅

**Comment by matuzalemsteles** [comment]
Okay 😆, we'd better keep it as it is.

**Comment by jbalsas** [comment]
I think whatever organization we come up with is just arbitrary. You then need to remember where you would’ve put things, and eventually you’ll keep wanting to nest further. Keeping it flat for now seems just simpler at this point imho :)

**Comment by matuzalemsteles** [comment]
🤔 It makes sense to me, I agree with the part we will want to nest things ... But I think the organization is necessary to continue to evolve, when it is stagnant can get to the point that it is no longer sustainable and need to re-organize. In other words, we always make the decision to organize when something is not sustainable or it does not make sense to other people ... I think that with a precocious organization this changes, but of course, based on how this will behave in the future.

Okay, Thanks @jbalsas by reflection! 😅

**Comment by jbalsas** [comment]
Thanks for bringing this up, @matuzalemsteles, it's always good to voice your opinion even if we see things different!

I'm closing it for now, but if everyone else agrees on this, we can reconsider :)

Sometimes less is more!!
