### ISSUE TITLE
ClayNavbar

### ISSUE THREAD

**Issue by carloslancha** [metal/metal-clay-components#130]
We need to update the markup

**Comment by matuzalemsteles** [comment]
Hey @carloslancha, The current markup is different from  [LEXI-166](https://issues.liferay.com/browse/LEXI-166), we change and add dropdown when the number of tabs goes over the physical size of the navbar?

**Comment by matuzalemsteles** [comment]
I'm working on the update of `ClayNavbar` and I'm having some impasses with the SSR for the use case.

The definition of Dropdown usage for the lexicon team:
> When the number of tabs goes over the physical size of the navbar, the overflowing tabs get collapse into the last one. This tabs are accessible through a dropdown menu.

The problem that to check this is only when the `menus` are attached in the dom, so I'm can calculate its size, so we will have to do this makeup by javascript to work as expected.

@jbalsas, @carloslancha what do you think about this?

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, let's keep moving for now without implementing this feature. Let's just update the markup for now so it works properly and we can work this out later on. We might need to sit with the Lexicon team to offer alternatives.

Let's just do what's clear right now and keep moving! :)
