### ISSUE TITLE
Export WebComponents

### ISSUE THREAD

**Issue by jbalsas** [metal/metal-clay-components#138]
[Metal.js@2.14.0](https://github.com/metal/metal.js/releases/tag/v2.14.0) is out, and with it the possibility of [generating WebComponents automatically](https://metaljs.com/docs/guides/web-components.html)

We should update all clay components so that they are exposed as WebComponents as well!

/cc @carloslancha, @matuzalemsteles

**Comment by matuzalemsteles** [comment]
Awesome 🎉.

Will we use a polyfill to support the older browsers in Clay? With the use of WebComponents.

**Comment by robframpton** [comment]
Hey @matuzalemsteles 

Yeah the polyfill is necessary for some browsers. However, it should degrade gracefully if web components are not supported. So we don't need to force people to load the polyfill.
