### ISSUE TITLE
Remove metal-* UI components dependencies

### ISSUE THREAD

**Issue by jbalsas** [metal/metal-clay-components#145]
It has been decided to reduce the metal.js surface to only core+plugins as it was always intended.

For that reason, we have already started deprecating and archiving all the ui-related metal components. We should remove all dependencies in this project like `metal-dropdown` and keep our own versions as they will no longer be available in the future.

**Comment by jbalsas** [comment]
Don't we have any other dependency other than `metal-dropdown`?

**Comment by matuzalemsteles** [comment]
Hey @jbalsas, Yes, we only had `metal-dropdown` as a dependency. 🙂

**Comment by jbalsas** [comment]
Awesome! 👏
