### ISSUE TITLE
Correct way to sort imports

### ISSUE THREAD

**Issue by julien** [metal/metal-clay-components#149]
At the moment, we have different ways of "sorting" imports and it would be nice to have a consistent way of doing it.

Here's an example to explain this a bit further.

```bash
# let's create a file with some content
cat>>test.js
import {Config} from 'metal-state';
import Component from 'metal-component';
import templates from './MyTemplate.soy.js';
# C-d to save and exit
```
 If you use the [`sort`](https://www.computerhope.com/unix/usort.htm) command 

```bash
sort test.js
````

The output is the following:

```js
import Component from 'metal-component';
import templates from './MyTemplate.soy.js';
import {Config} from 'metal-state';
```

However, if you open this same `test.js` file with [VSCode](https://code.visualstudio.com/) the and use the `Sort Lines Ascending` (which can be accessed with the `CMD` + `Shift` + `p` key combination) the output is different and looks like this:

```js
import {Config} from 'metal-state';
import Component from 'metal-component';
import templates from './MyTemplate.soy.js';
```

Let's find a consistent way of doing this.
 
Maybe [eslint-plugin-import-order-autofix](https://github.com/AlexJuarez/eslint-plugin-import-order-autofix) could be a solution.

**Comment by jbalsas** [comment]
Hey @julien, the convention (will be documented soon in the guidelines) is to have 2 blocks in this order:
- Absolute imports
- Relative imports

**The blogs should be sorted alphabetically within the block and there should be an empty line between them.**

Keep in mind that we don't use `eslint` to format, so it will warn, but not autoformat. We can enforce it via linting (and we probably will), but we will still need to manually change it.

We actually looked at https://github.com/renke/import-sort for this, but at this point I'd prefer to keep the dependencies to a minimum until we get the guidelines more consistent across projects.

**Comment by julien** [comment]
Thanks for claryfying @jbalsas,

I'll stick to these conventions.
