### ISSUE TITLE
Why are we using yarn?

### ISSUE THREAD

**Issue by bryceosterhaus** [metal/metal-clay-components#190]
Saw that we use `yarn` for this repo. I was wondering why we switched to this since Metal.js repo is using `npm`. IMO its a little confusing to change up tooling between repos. I have nothing against yarn, I just prefer consistency between repos in the org.

**Comment by matuzalemsteles** [comment]
Hey @bryceosterhaus, That looks weird even at first glance. but we had several problems with dependency management and in fact we are only just using the workspace tool of yarn. You can find the reasons for this exchange in pr #78.

You can still continue using `npm run lerna` to wrap and install the required dependencies. And yet `npm run build`, `npm run test`, `npm run build`...

**Comment by bryceosterhaus** [comment]
I see. Thanks for the response @matuzalemsteles
