### ISSUE TITLE
lerna run test could not find module

### ISSUE THREAD

**Issue by pat270** [metal/metal-clay-components#20]
When running `lerna run test` it's unable to find a local package.

  Uncaught Error: Could not find module '../../metal-quartz-icon/src/MetalQuartzIcon' from '/metal-quartz-components/packages/metal-quartz-link/src/MetalQuartzLink.js'
  at node_modules/karma-commonjs/client/commonjs_bridge.js:85

**Comment by fernandosouza** [comment]
Hey, @pat270. I'm already working on this. There is [another issue](https://github.com/metal/metal-quartz-components/issues/16)  that mentions this.

MetalJS also uses Lerna and it has not this issue. By my research, it's because it is using Browserify to bundle files.

:)

**Comment by pat270** [comment]
I didn't realize this was a duplicate. Closing, thanks @fernandosouza.
