### ISSUE TITLE
Enable fully mcritic testing 

### ISSUE THREAD

**Issue by jbalsas** [metal/metal-clay-components#204]
We are currently ignoring a lot of packages from soy linting because it gives us problems. We need to enable it again or we risk introducing bugs and inconsistencies.

**Comment by carloslancha** [comment]
For this we need to provide mcritic the ability to recognize correctly the modules imports.

**Comment by jbalsas** [comment]
This is already implemented in `mcritic`, and we're using it [here](https://github.com/metal/metal-clay-components/blob/master/.soycriticrc.json#L2-L3)

The problem is that we have 2 import flavours:
- `import 'clay-icon'`;
- `import './ClayFooBase'`

The same re-write won't work for the second import, so we need to add the option of multiple import rewrites :(

**Comment by carloslancha** [comment]
In fact we have 3 import flavours:

- import 'clay-icon';
- import './ClayFooBase'
- import {ClayActionsDropdown} from 'clay-dropdown'

So we need to take in account also the named exports. I've send a pr to fix both problems: https://github.com/metal/metal-soy-critic/pull/14
