### ISSUE TITLE
Create Metal Clay Checkbox Component

### ISSUE THREAD

**Issue by pat270** [metal/metal-clay-components#21]

**Comment by anitaderiane** [comment]
https://issues.liferay.com/browse/IFI-55

**Comment by fernandosouza** [comment]
I am going to working on this one, @pat270.

**Comment by fernandosouza** [comment]
Sorry @pat270. I've just seen you already sent a pull request.

**Comment by carloslancha** [comment]
Since we now have https://github.com/metal/metal-clay-components/tree/master/packages/clay-checkbox can we close this issue?
