### ISSUE TITLE
Clay V2/BS4 Components Migration List

### ISSUE THREAD

**Issue by pat270** [metal/metal-clay-components#29]
This issue is keeping track of Clay V2 migration

Components that are safe to work on:
Alerts
Badges, Labels, Stickers
Breadcrumbs
Buttons
Dropdowns
Form Elements
Form Element Input groups
Icons Clay SVG's
Modals
Multi Step Nav
Pagination
Panels (Keeping Panels)
Popovers
Progress Bars
Tables
Timelines
Toggles

(REMOVED) Figures
(REMOVED) Header Toolbar
(REMOVED) Icons Font Awesome
(REMOVED) Icons Glyphicons
(REMOVED) Nameplates
(REMOVED) Pager
(REMOVED) Toolbars
(REMOVED) User Icons

Components still pending:
Form Element Validation
Cards
List Groups
Loading Indicators (might remove this)
Mangement Bar
Navigation Bar
Navbars (This is a base component that is used by Management Bar, Navigation Bar, and potentially Other Bars)
Nav
Nav Underline
Nav Tabs
Sidebar
Subnav
Tooltips

**Comment by brunobasto** [comment]
hey @pat270, is this still up to date?

**Comment by pat270** [comment]
I just updated it. I had to move all the nav stuff back to pending. The nav designs were updated since I last wrote this and got some extra requirements from the Faro team.

**Comment by carloslancha** [comment]
The list of components ready for development is already in the board https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=2883&view=detail so we don't need to have this info duplicated and probably outdated here.

Please, close the issue to avoid confusion. Thx!
