### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by fernandosouza** [metal/metal-clay-components#39]
What do you guys think about we use the same .editorconfig of Metal Components?
https://github.com/metal/metal-tabs/blob/master/.editorconfig

Even we don't pick the same configuration I think we should use any.

cc. @jbalsas, @pat270, @Robert-Frampton, @brunobasto

**Comment by jbalsas** [comment]
I don't see why not... on the other hand, we have prettier enabled now, so is it really needed? What do you guys think?

**Comment by robframpton** [comment]
As long as the config matches prettier I'm fine with including it still.

**Comment by jbalsas** [comment]
Hey @carloslancha, can you update to `prettier@1.6.0` so we can move the settings to a `.prettierrc` file? I think that solves it better since you can configure your IDEs to run `prettier` on save.

I think that should address this.

**Comment by carloslancha** [comment]
https://github.com/metal/metal-clay-components/pull/66

**Comment by jbalsas** [comment]
Done!
