### ISSUE TITLE
Create Metal Quartz Button Component

### ISSUE THREAD

**Issue by pat270** [metal/metal-clay-components#4]

**Comment by jbalsas** [comment]
Here's the definition document: https://github.com/metal/metal-quartz-components/tree/master/packages/metal-quartz-icon

**Comment by fernandosouza** [comment]
@jbalsas, is this link you posted above right? You supposed to share the button definition but the link goes to the `metal-quartz-icon` component.

**Comment by jbalsas** [comment]
This is created :)
