### ISSUE TITLE
Transitive dependencies

### ISSUE THREAD

**Issue by carloslancha** [metal/metal-clay-components#72]
When we use a component as a dependency that uses another component as a dependency we need to add both as dependencies in our component in order to make soy compile working.

The problem is with `metalsoy --soyDeps`, as a workaround we made this:

https://github.com/metal/metal-clay-components/pull/71/commits/7319a9451cb303d8c51ba5dfd6da70f08d765bfd#diff-487d9b9c11d483b0c92610dbf8612825R21

**Comment by matuzalemsteles** [comment]
Hey @carloslancha,

In the case of a component having two dependencies and both depend on another component, `metalsoy --soyDeps` accuses` Undefined template` and in case I add its example it accuses `Template 'ClayIcon.render' already defined`. Like the #68 case.

Do you have any insight into this?

**Comment by julien** [comment]
I'll have a look into it.

**Comment by carloslancha** [comment]
Fixed with https://github.com/metal/metal-clay-components/pull/82
