### ISSUE TITLE
Demos Background

### ISSUE THREAD

**Issue by carloslancha** [metal/metal-clay-components#87]
All clay components should be shown over white background instead of current grey.

**Comment by matuzalemsteles** [comment]
Hey @carloslancha,

Would it be to follow Lexicon's demonstration standards?

**Comment by carloslancha** [comment]
@matuzalemsteles  Yes, 'cause in cases like disabled unchecked checkboxes with current color you cannot see the checkbox because is in the same color as the background.

**Comment by carloslancha** [comment]
https://github.com/metal/metal-clay-components/pull/99
